//
//  SearchCriteriaWorker.swift
//  CleaniTunes
//
//  Created by hager gamal on 1/29/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SearchCriteriaWorker {
    var resultsStore: ResultsStoreProtocol
    
    init(resultsStore: ResultsStoreProtocol = ResultsAPI()) {
        self.resultsStore = resultsStore
    }
    
    func fetchResults(request: SearchCriteria.GetResults.Request, completionHandler: @escaping ([Result], ResultsStoreError?) -> Void) {
        resultsStore.fetchResults(request: request) { (results, error) in
            DispatchQueue.main.async {
                completionHandler(results, error)
            }
        }
    }
}
protocol ResultsStoreProtocol {
    
    func fetchResults(request: SearchCriteria.GetResults.Request, completionHandler: @escaping ([Result], ResultsStoreError?) -> Void)
}

enum ResultsStoreError: Equatable, Error {
    case cannotFetch
    var message: String {
        switch self {
        case .cannotFetch:
            return "Can not find results right now.\nPlease try again later."
        }
    }
}
