//
//  SearchCriteriaPresenter.swift
//  CleaniTunes
//
//  Created by hager gamal on 1/29/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchCriteriaPresentationLogic {
    func presentResultsList(response: SearchCriteria.GetResults.Response)
    func presentNoData()
    func presentError(error: String)
}

class SearchCriteriaPresenter: SearchCriteriaPresentationLogic {
    weak var viewController: SearchCriteriaDisplayLogic?
    
    init(viewController: SearchCriteriaDisplayLogic) {
        self.viewController = viewController
    }
    
    func presentError(error: String) {
        viewController?.presentError(error: error)
    }
    
    func presentNoData() {
        viewController?.showNoDataError()
    }
    
    func presentResultsList(response: SearchCriteria.GetResults.Response) {
        let viewModel = SearchCriteria.GetResults.ViewModel(results: response.results)
        viewController?.navigateToListing(viewModel: viewModel)
    }
}
