//
//  SearchCriteriaRouter.swift
//  CleaniTunes
//
//  Created by hager gamal on 1/29/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchCriteriaRoutingLogic {
    func navigateToResultList(result: [Result])
    func navigateToMediaTypeSelection(selectedMediaTypes: [String])
}

protocol SearchCriteriaDataPassing {
    var dataStore: SearchCriteriaDataStore? { get }
}

class SearchCriteriaRouter: NSObject, SearchCriteriaRoutingLogic, SearchCriteriaDataPassing {
    weak var viewController: SearchCriteriaViewController?
    var dataStore: SearchCriteriaDataStore?
    
    // MARK: Navigation
    
    func navigateToResultList(result: [Result]) {
        let storyboard = viewController?.storyboard
        guard let destinationVC = storyboard?.instantiateViewController(withIdentifier: "ResultListingViewController") as? ResultListingViewController else { return }
        var dataStore = destinationVC.router?.dataStore
        dataStore?.results = result
        navigateToShowResultsList(source: viewController!, destination: destinationVC)
    }
    
    func navigateToMediaTypeSelection(selectedMediaTypes: [String]) {
        let storyboard = viewController?.storyboard
        guard let destinationVC = storyboard?.instantiateViewController(withIdentifier: "MediaTypeSelectionViewController") as? MediaTypeSelectionViewController else { return }
        destinationVC.delegate = viewController
        var dataStore = destinationVC.router?.dataStore
        dataStore?.selectedMediaTypes = selectedMediaTypes
        navigateToMediaType(source: viewController!, destination: destinationVC)
    }
    
    // MARK: Passing data
    
    func navigateToShowResultsList(source: SearchCriteriaViewController, destination: ResultListingViewController) {
        source.show(destination, sender: nil)
    }
    
    func navigateToMediaType(source: SearchCriteriaViewController, destination: MediaTypeSelectionViewController) {
        source.show(destination, sender: nil)
    }
}
