//
//  ResultDetailsPresenter.swift
//  CleaniTunes
//
//  Created by hager gamal on 1/29/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ResultDetailsPresentationLogic {
    func presentResultDetails(result: ResultModel)
}

class ResultDetailsPresenter: ResultDetailsPresentationLogic {
    
    weak var viewController: ResultDetailsDisplayLogic?
    
    // MARK: present Details
    
    func presentResultDetails(result: ResultModel) {
        let details = ResultDetails.GetDetails.ViewModel.Details(trackName: result.trackName, trackImageURL: result.trackImageURL, artistName: result.artistName, previewUrl: result.previewUrl, longDescription: result.longDescription, wrapperType: result.wrapperType.displayType)
        
        let viewModel = ResultDetails.GetDetails.ViewModel(displayedDetails: details)
        viewController?.displayResultDetails(viewModel: viewModel)
    }
}
