//
//  ResultListingInteractor.swift
//  CleaniTunes
//
//  Created by hager gamal on 1/29/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ResultListingBusinessLogic {
    func getResults()
    func setDisplayMode(mode: DisplayMode)
}

protocol ResultListingDataStore {
    var results: [Result]? {get set}
}

class ResultListingInteractor: ResultListingBusinessLogic, ResultListingDataStore {
    
    var results: [Result]?
    
    var presenter: ResultListingPresentationLogic?
    
    // MARK: Actions
    
    func getResults() {
        presenter?.presentResult(results: results ?? [])
    }
    
    func setDisplayMode(mode: DisplayMode) {
        presenter?.setDisplayMode(mode: mode)
    }
}
