//
//  ResultListingRouter.swift
//  CleaniTunes
//
//  Created by hager gamal on 1/29/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ResultListingRoutingLogic {
    func routeToDetails(resultDetails: ResultModel)
}

protocol ResultListingDataPassing {
    var dataStore: ResultListingDataStore? { get }
}

class ResultListingRouter: NSObject, ResultListingRoutingLogic, ResultListingDataPassing {
    weak var viewController: ResultListingViewController?
    var dataStore: ResultListingDataStore?
    
    // MARK: Routing
    
    func routeToDetails(resultDetails: ResultModel) {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        if let destinationVC = storyboard.instantiateViewController(withIdentifier: "ResultDetailsViewController") as? ResultDetailsViewController {
            var destinationDS = destinationVC.router!.dataStore!
            passDataToShowDetails(source: dataStore!, destination: &destinationDS, resultDetails: resultDetails)
            navigateToDtails(source: viewController!, destination: destinationVC)
        }
    }
    
    func passDataToShowDetails(source: ResultListingDataStore, destination: inout ResultDetailsDataStore, resultDetails: ResultModel) {
      destination.result = resultDetails
    }
    // MARK: Navigation
    
    func navigateToDtails(source: ResultListingViewController, destination: ResultDetailsViewController) {
        source.show(destination, sender: nil)
    }
    
}
