//
//  MediaTypeSelectionPresenter.swift
//  CleaniTunes
//
//  Created by hager gamal on 1/29/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MediaTypeSelectionPresentationLogic {
    func presentMediaTypes(mediaTypes: [MediaType] )
}

class MediaTypeSelectionPresenter: MediaTypeSelectionPresentationLogic {
    weak var viewController: MediaTypeSelectionDisplayLogic?
    
    // MARK: present MediaTypes
    
    func presentMediaTypes(mediaTypes: [MediaType]) {
        let viewModel = MediaTypeSelection.GetMediaType.ViewModel(mediaTypes: mediaTypes)
        viewController?.displayMediaTypes(viewModel: viewModel)
    }
}
