//
//  MediaTypeSelectionModels.swift
//  CleaniTunes
//
//  Created by hager gamal on 1/29/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MediaTypeSelection {
    // MARK: Use cases
    
    enum GetMediaType {
        struct ViewModel {
            
            struct MediaType {
                var title: String
                var isSelected: Bool
                var displayedTitle: String
            }
            var mediaTypes: [MediaType]
        }
    }
}
